name: personal_website
description: My own personal website. https://nathans.dev
publish_to: 'none'
version: 2.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  
  # Flutterfall
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1

  seo_renderer: ^0.3.0
  fluttertoast: ^8.0.9
  auto_size_text: ^3.0.0

  personal_theme:
    git:
      url: git@github.com:nathanielxd/personal-flutter-theme.git
      ref: master

  fast_strings:
    git:
      url: git@github.com:nathanielxd/fast-strings.git
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Manrope
      fonts:
        - asset: fonts/Manrope-Regular.ttf
        - asset: fonts/Manrope-Bold.ttf
          weight: 700
