name: personal_website
description: My own personal website. Check it out at https://nathans.dev
publish_to: 'none'
version: 2.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:

  flutter:
    sdk: flutter

  flutter_web_plugins:
    sdk: flutter
  
  # Flutterfall
  equatable:
  flutter_bloc:

  # Presentation
  personal_theme:
    git:
      url: git@github.com:nathanielxd/personal-flutter-theme.git
      ref: master
  
  seo_renderer: ^0.3.0
  fluttertoast:
  auto_size_text:

dev_dependencies:
  flutter_lints:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Manrope
      fonts:
        - asset: fonts/Manrope-Regular.ttf
        - asset: fonts/Manrope-Bold.ttf
          weight: 700